### see all the tasks
GET  http://localhost:3000

### delete especific task
DELETE http://localhost:3000/Eascritorio

### this create a task 
POST http://localhost:3000
Content-Type: application/json

 {
    "task_description": "Organaizar escritorio",
    "task_title": "Eascritorio",
    "task_situation": false
  }
  
### get especific task with the title
GET  http://localhost:3000/Hacer manana

### update task
PATCH  http://localhost:3000/Supermercados
Content-Type: application/json

 {
    "task_description": "Leer un libro",
    "task_title": "Supermercado",
    "task_situation": true
  } 

